In [ ]:
# NLP Text Classification

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import string
import nltk

In [ ]:
data = {

  "text": [

    "I love working with data and statistics",

    "Data visualization helps understand trends",

    "Data analysis improves business decisions",

    "Machine learning models can predict outcomes",

    "Training models requires a lot of data",

    "Supervised learning uses labeled data",

    "AI is transforming industries rapidly",

    "Artificial intelligence powers smart assistants",

    "AI systems can automate complex tasks",

    "Machine learning improves recommendation systems",

    "Data science combines statistics and programming",

    "Artificial intelligence enables self driving cars"

  ],

   

  "label": [

    "data_science",

    "data_science",

    "data_science",

    "machine_learning",

    "machine_learning",

    "machine_learning",

    "artificial_intelligence",

    "artificial_intelligence",

    "artificial_intelligence",

    "machine_learning",

    "data_science",

    "artificial_intelligence"

  ]

}

df = pd.DataFrame(data)
df

                                                 text                    label
0             I love working with data and statistics             data_science
1          Data visualization helps understand trends             data_science
2           Data analysis improves business decisions             data_science
3        Machine learning models can predict outcomes         machine_learning
4              Training models requires a lot of data         machine_learning
5               Supervised learning uses labeled data         machine_learning
6               AI is transforming industries rapidly  artificial_intelligence
7     Artificial intelligence powers smart assistants  artificial_intelligence
8               AI systems can automate complex tasks  artificial_intelligence
9    Machine learning improves recommendation systems         machine_learning
10   Data science combines statistics and programming             data_science
11  Artificial intelligence enables self driving cars  artificial_intelligence

In [ ]:
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from nltk.stem import WordNetLemmatizer

In [ ]:
df["clean_text"] = df["text"].str.lower()
df

,text,label,clean_text
0,I love working with data and statistics,i love working with data and statistics,i love working with data and statistics
1,Data visualization helps understand trends,data visualization helps understand trends,data visualization helps understand trends
2,Data analysis improves business decisions,data analysis improves business decisions,data analysis improves business decisions
3,Machine learning models can predict outcomes,machine learning models can predict outcomes,machine learning models can predict outcomes
4,Training models requires a lot of data,training models requires a lot of data,training models requires a lot of data
5,Supervised learning uses labeled data,supervised learning uses labeled data,supervised learning uses labeled data
6,AI is transforming industries rapidly,ai is transforming industries rapidly,ai is transforming industries rapidly
7,Artificial intelligence powers smart assistants,artificial intelligence powers smart assistants,artificial intelligence powers smart assistants
8,AI systems can automate complex tasks,ai systems can automate complex tasks,ai systems can automate complex tasks
9,Machine learning improves recommendation systems,machine learning improves recommendation systems,machine learning improves recommendation systems
10,Data science combines statistics and programming,data science combines statistics and programming,data science combines statistics and programming
11,Artificial intelligence enables self driving cars,artificial intelligence enables self driving cars,artificial intelligence enables self driving cars

In [ ]:
df["clean_text"]=df["clean_text"].str.replace(f" [{string.punctuation}]", "", regex=True)
df.head()

,text,label,clean_text
0,I love working with data and statistics,i love working with data and statistics,i love working with data and statistics
1,Data visualization helps understand trends,data visualization helps understand trends,data visualization helps understand trends
2,Data analysis improves business decisions,data analysis improves business decisions,data analysis improves business decisions
3,Machine learning models can predict outcomes,machine learning models can predict outcomes,machine learning models can predict outcomes
4,Training models requires a lot of data,training models requires a lot of data,training models requires a lot of data

In [ ]:
df["tokens"]=df["clean_text"].apply(word_tokenize)
df

,text,label,clean_text,tokens
0,I love working with data and statistics,i love working with data and statistics,i love working with data and statistics,"[i, love, working, with, data, and, statistics]"
1,Data visualization helps understand trends,data visualization helps understand trends,data visualization helps understand trends,"[data, visualization, helps, understand, trends]"
2,Data analysis improves business decisions,data analysis improves business decisions,data analysis improves business decisions,"[data, analysis, improves, business, decisions]"
3,Machine learning models can predict outcomes,machine learning models can predict outcomes,machine learning models can predict outcomes,"[machine, learning, models, can, predict, outc..."
4,Training models requires a lot of data,training models requires a lot of data,training models requires a lot of data,"[training, models, requires, a, lot, of, data]"
5,Supervised learning uses labeled data,supervised learning uses labeled data,supervised learning uses labeled data,"[supervised, learning, uses, labeled, data]"
6,AI is transforming industries rapidly,ai is transforming industries rapidly,ai is transforming industries rapidly,"[ai, is, transforming, industries, rapidly]"
7,Artificial intelligence powers smart assistants,artificial intelligence powers smart assistants,artificial intelligence powers smart assistants,"[artificial, intelligence, powers, smart, assi..."
8,AI systems can automate complex tasks,ai systems can automate complex tasks,ai systems can automate complex tasks,"[ai, systems, can, automate, complex, tasks]"
9,Machine learning improves recommendation systems,machine learning improves recommendation systems,machine learning improves recommendation systems,"[machine, learning, improves, recommendation, ..."
10,Data science combines statistics and programming,data science combines statistics and programming,data science combines statistics and programming,"[data, science, combines, statistics, and, pro..."
11,Artificial intelligence enables self driving cars,artificial intelligence enables self driving cars,artificial intelligence enables self driving cars,"[artificial, intelligence, enables, self, driv..."

In [ ]:
stop_words = set(stopwords.words("english"))
df["tokens"] = df["tokens"].apply(lambda x: [word for word in x if word not in stop_words])
df

,text,label,clean_text,tokens
0,I love working with data and statistics,i love working with data and statistics,i love working with data and statistics,"[love, working, data, statistics]"
1,Data visualization helps understand trends,data visualization helps understand trends,data visualization helps understand trends,"[data, visualization, helps, understand, trends]"
2,Data analysis improves business decisions,data analysis improves business decisions,data analysis improves business decisions,"[data, analysis, improves, business, decisions]"
3,Machine learning models can predict outcomes,machine learning models can predict outcomes,machine learning models can predict outcomes,"[machine, learning, models, predict, outcomes]"
4,Training models requires a lot of data,training models requires a lot of data,training models requires a lot of data,"[training, models, requires, lot, data]"
5,Supervised learning uses labeled data,supervised learning uses labeled data,supervised learning uses labeled data,"[supervised, learning, uses, labeled, data]"
6,AI is transforming industries rapidly,ai is transforming industries rapidly,ai is transforming industries rapidly,"[ai, transforming, industries, rapidly]"
7,Artificial intelligence powers smart assistants,artificial intelligence powers smart assistants,artificial intelligence powers smart assistants,"[artificial, intelligence, powers, smart, assi..."
8,AI systems can automate complex tasks,ai systems can automate complex tasks,ai systems can automate complex tasks,"[ai, systems, automate, complex, tasks]"
9,Machine learning improves recommendation systems,machine learning improves recommendation systems,machine learning improves recommendation systems,"[machine, learning, improves, recommendation, ..."
10,Data science combines statistics and programming,data science combines statistics and programming,data science combines statistics and programming,"[data, science, combines, statistics, programm..."
11,Artificial intelligence enables self driving cars,artificial intelligence enables self driving cars,artificial intelligence enables self driving cars,"[artificial, intelligence, enables, self, driv..."

In [ ]:
lemmatizer = WordNetLemmatizer()
df["lemma"]=df["tokens"].apply(lambda words:[lemmatizer.lemmatize(w) for w in words])
df

,text,label,clean_text,tokens,lemma
0,I love working with data and statistics,i love working with data and statistics,i love working with data and statistics,"[love, working, data, statistics]","[love, working, data, statistic]"
1,Data visualization helps understand trends,data visualization helps understand trends,data visualization helps understand trends,"[data, visualization, helps, understand, trends]","[data, visualization, help, understand, trend]"
2,Data analysis improves business decisions,data analysis improves business decisions,data analysis improves business decisions,"[data, analysis, improves, business, decisions]","[data, analysis, improves, business, decision]"
3,Machine learning models can predict outcomes,machine learning models can predict outcomes,machine learning models can predict outcomes,"[machine, learning, models, predict, outcomes]","[machine, learning, model, predict, outcome]"
4,Training models requires a lot of data,training models requires a lot of data,training models requires a lot of data,"[training, models, requires, lot, data]","[training, model, requires, lot, data]"
5,Supervised learning uses labeled data,supervised learning uses labeled data,supervised learning uses labeled data,"[supervised, learning, uses, labeled, data]","[supervised, learning, us, labeled, data]"
6,AI is transforming industries rapidly,ai is transforming industries rapidly,ai is transforming industries rapidly,"[ai, transforming, industries, rapidly]","[ai, transforming, industry, rapidly]"
7,Artificial intelligence powers smart assistants,artificial intelligence powers smart assistants,artificial intelligence powers smart assistants,"[artificial, intelligence, powers, smart, assi...","[artificial, intelligence, power, smart, assis..."
8,AI systems can automate complex tasks,ai systems can automate complex tasks,ai systems can automate complex tasks,"[ai, systems, automate, complex, tasks]","[ai, system, automate, complex, task]"
9,Machine learning improves recommendation systems,machine learning improves recommendation systems,machine learning improves recommendation systems,"[machine, learning, improves, recommendation, ...","[machine, learning, improves, recommendation, ..."
10,Data science combines statistics and programming,data science combines statistics and programming,data science combines statistics and programming,"[data, science, combines, statistics, programm...","[data, science, combine, statistic, programming]"
11,Artificial intelligence enables self driving cars,artificial intelligence enables self driving cars,artificial intelligence enables self driving cars,"[artificial, intelligence, enables, self, driv...","[artificial, intelligence, enables, self, driv..."